Vagrant.configure("2") do |config|
  config.vm.define "puppetdb" do |c|
    c.vm.box = "ubuntu-server-12042-x64-vbox4210"
    c.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"
    c.vm.hostname = 'puppetdb.singlenode.vm'
    c.vm.provision :puppet do |p|
      p.manifest_file = "site.pp"
      p.module_path = ["modules", "site"]
    end
    c.vm.network :forwarded_port, guest: 5432, host: 15432
    c.vm.network :forwarded_port, guest: 8080, host: 18080
    c.vm.network :private_network, ip: "192.168.50.3"
  end

  config.vm.define "client1" do |c|
    c.vm.box = "ubuntu-server-12042-x64-vbox4210"
    c.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"
    c.vm.hostname = 'client1.singlenode.vm'
    c.vm.provision :puppet do |p|
      p.manifest_file = "site.pp"
      p.module_path = ["modules", "site"]
    end
    c.vm.network :private_network, ip: "192.168.50.4"
  end

  config.vm.define "client2" do |c|
    c.vm.box = "ubuntu-server-12042-x64-vbox4210"
    c.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"
    c.vm.hostname = 'client2.singlenode.vm'
    c.vm.provision :puppet do |p|
      p.manifest_file = "site.pp"
      p.module_path = ["modules", "site"]
    end
    c.vm.network :private_network, ip: "192.168.50.5"
  end
end
